import { readdirSync, statSync, writeFileSync } from "fs";
import { join, relative } from "path";

const OUT_DIR = "./out";
const OUTPUT = "./embedded-files.ts";

function walk(dir: string): string[] {
  const result: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) result.push(...walk(full));
    else result.push(full);
  }
  return result;
}

const files = walk(OUT_DIR);
const imports: string[] = [];
const entries: string[] = [];

files.forEach((file, i) => {
  const key = "/" + relative(OUT_DIR, file).replace(/\\/g, "/");
  imports.push(`import f${i} from ${JSON.stringify("./" + file)} with { type: "file" };`);
  entries.push(`  ${JSON.stringify(key)}: f${i}`);
});

const code = [
  "// Auto-generated by bundle-assets.ts — do not edit",
  ...imports,
  "",
  `export const FILES: Record<string, string> = {`,
  entries.join(",\n"),
  `};`,
  "",
].join("\n");

writeFileSync(OUTPUT, code);
console.log(`Embedded ${files.length} files → ${OUTPUT}`);
